export type PhonePrefix = {
  iso: string;
  dialCode: string;
  name: string;
};

export const PHONE_PREFIXES: PhonePrefix[] = [
  { iso: "AD", dialCode: "+376", name: "Andorra" },
  { iso: "AE", dialCode: "+971", name: "United Arab Emirates" },
  { iso: "AF", dialCode: "+93", name: "Afghanistan" },
  { iso: "AG", dialCode: "+1268", name: "Antigua and Barbuda" },
  { iso: "AL", dialCode: "+355", name: "Albania" },
  { iso: "AM", dialCode: "+374", name: "Armenia" },
  { iso: "AO", dialCode: "+244", name: "Angola" },
  { iso: "AR", dialCode: "+54", name: "Argentina" },
  { iso: "AT", dialCode: "+43", name: "Austria" },
  { iso: "AU", dialCode: "+61", name: "Australia" },
  { iso: "AZ", dialCode: "+994", name: "Azerbaijan" },
  { iso: "BA", dialCode: "+387", name: "Bosnia and Herzegovina" },
  { iso: "BB", dialCode: "+1246", name: "Barbados" },
  { iso: "BD", dialCode: "+880", name: "Bangladesh" },
  { iso: "BE", dialCode: "+32", name: "Belgium" },
  { iso: "BG", dialCode: "+359", name: "Bulgaria" },
  { iso: "BH", dialCode: "+973", name: "Bahrain" },
  { iso: "BI", dialCode: "+257", name: "Burundi" },
  { iso: "BJ", dialCode: "+229", name: "Benin" },
  { iso: "BN", dialCode: "+673", name: "Brunei" },
  { iso: "BO", dialCode: "+591", name: "Bolivia" },
  { iso: "BR", dialCode: "+55", name: "Brazil" },
  { iso: "BS", dialCode: "+1242", name: "Bahamas" },
  { iso: "BT", dialCode: "+975", name: "Bhutan" },
  { iso: "BW", dialCode: "+267", name: "Botswana" },
  { iso: "BY", dialCode: "+375", name: "Belarus" },
  { iso: "BZ", dialCode: "+501", name: "Belize" },
  { iso: "CA", dialCode: "+1", name: "Canada" },
  { iso: "CD", dialCode: "+243", name: "Congo (DRC)" },
  { iso: "CF", dialCode: "+236", name: "Central African Republic" },
  { iso: "CG", dialCode: "+242", name: "Congo" },
  { iso: "CH", dialCode: "+41", name: "Switzerland" },
  { iso: "CI", dialCode: "+225", name: "Côte d'Ivoire" },
  { iso: "CL", dialCode: "+56", name: "Chile" },
  { iso: "CM", dialCode: "+237", name: "Cameroon" },
  { iso: "CN", dialCode: "+86", name: "China" },
  { iso: "CO", dialCode: "+57", name: "Colombia" },
  { iso: "CR", dialCode: "+506", name: "Costa Rica" },
  { iso: "CU", dialCode: "+53", name: "Cuba" },
  { iso: "CV", dialCode: "+238", name: "Cape Verde" },
  { iso: "CY", dialCode: "+357", name: "Cyprus" },
  { iso: "CZ", dialCode: "+420", name: "Czech Republic" },
  { iso: "DE", dialCode: "+49", name: "Germany" },
  { iso: "DJ", dialCode: "+253", name: "Djibouti" },
  { iso: "DK", dialCode: "+45", name: "Denmark" },
  { iso: "DM", dialCode: "+1767", name: "Dominica" },
  { iso: "DO", dialCode: "+1809", name: "Dominican Republic" },
  { iso: "DZ", dialCode: "+213", name: "Algeria" },
  { iso: "EC", dialCode: "+593", name: "Ecuador" },
  { iso: "EE", dialCode: "+372", name: "Estonia" },
  { iso: "EG", dialCode: "+20", name: "Egypt" },
  { iso: "ER", dialCode: "+291", name: "Eritrea" },
  { iso: "ES", dialCode: "+34", name: "Spain" },
  { iso: "ET", dialCode: "+251", name: "Ethiopia" },
  { iso: "FI", dialCode: "+358", name: "Finland" },
  { iso: "FJ", dialCode: "+679", name: "Fiji" },
  { iso: "FR", dialCode: "+33", name: "France" },
  { iso: "GA", dialCode: "+241", name: "Gabon" },
  { iso: "GB", dialCode: "+44", name: "United Kingdom" },
  { iso: "GD", dialCode: "+1473", name: "Grenada" },
  { iso: "GE", dialCode: "+995", name: "Georgia" },
  { iso: "GH", dialCode: "+233", name: "Ghana" },
  { iso: "GM", dialCode: "+220", name: "Gambia" },
  { iso: "GN", dialCode: "+224", name: "Guinea" },
  { iso: "GQ", dialCode: "+240", name: "Equatorial Guinea" },
  { iso: "GR", dialCode: "+30", name: "Greece" },
  { iso: "GT", dialCode: "+502", name: "Guatemala" },
  { iso: "GW", dialCode: "+245", name: "Guinea-Bissau" },
  { iso: "GY", dialCode: "+592", name: "Guyana" },
  { iso: "HN", dialCode: "+504", name: "Honduras" },
  { iso: "HR", dialCode: "+385", name: "Croatia" },
  { iso: "HT", dialCode: "+509", name: "Haiti" },
  { iso: "HU", dialCode: "+36", name: "Hungary" },
  { iso: "ID", dialCode: "+62", name: "Indonesia" },
  { iso: "IE", dialCode: "+353", name: "Ireland" },
  { iso: "IL", dialCode: "+972", name: "Israel" },
  { iso: "IN", dialCode: "+91", name: "India" },
  { iso: "IQ", dialCode: "+964", name: "Iraq" },
  { iso: "IR", dialCode: "+98", name: "Iran" },
  { iso: "IS", dialCode: "+354", name: "Iceland" },
  { iso: "IT", dialCode: "+39", name: "Italy" },
  { iso: "JM", dialCode: "+1876", name: "Jamaica" },
  { iso: "JO", dialCode: "+962", name: "Jordan" },
  { iso: "JP", dialCode: "+81", name: "Japan" },
  { iso: "KE", dialCode: "+254", name: "Kenya" },
  { iso: "KG", dialCode: "+996", name: "Kyrgyzstan" },
  { iso: "KH", dialCode: "+855", name: "Cambodia" },
  { iso: "KM", dialCode: "+269", name: "Comoros" },
  { iso: "KN", dialCode: "+1869", name: "Saint Kitts and Nevis" },
  { iso: "KR", dialCode: "+82", name: "South Korea" },
  { iso: "KW", dialCode: "+965", name: "Kuwait" },
  { iso: "KZ", dialCode: "+7", name: "Kazakhstan" },
  { iso: "LA", dialCode: "+856", name: "Laos" },
  { iso: "LB", dialCode: "+961", name: "Lebanon" },
  { iso: "LC", dialCode: "+1758", name: "Saint Lucia" },
  { iso: "LI", dialCode: "+423", name: "Liechtenstein" },
  { iso: "LK", dialCode: "+94", name: "Sri Lanka" },
  { iso: "LR", dialCode: "+231", name: "Liberia" },
  { iso: "LS", dialCode: "+266", name: "Lesotho" },
  { iso: "LT", dialCode: "+370", name: "Lithuania" },
  { iso: "LU", dialCode: "+352", name: "Luxembourg" },
  { iso: "LV", dialCode: "+371", name: "Latvia" },
  { iso: "LY", dialCode: "+218", name: "Libya" },
  { iso: "MA", dialCode: "+212", name: "Morocco" },
  { iso: "MC", dialCode: "+377", name: "Monaco" },
  { iso: "MD", dialCode: "+373", name: "Moldova" },
  { iso: "ME", dialCode: "+382", name: "Montenegro" },
  { iso: "MG", dialCode: "+261", name: "Madagascar" },
  { iso: "MK", dialCode: "+389", name: "North Macedonia" },
  { iso: "ML", dialCode: "+223", name: "Mali" },
  { iso: "MM", dialCode: "+95", name: "Myanmar" },
  { iso: "MN", dialCode: "+976", name: "Mongolia" },
  { iso: "MR", dialCode: "+222", name: "Mauritania" },
  { iso: "MT", dialCode: "+356", name: "Malta" },
  { iso: "MU", dialCode: "+230", name: "Mauritius" },
  { iso: "MV", dialCode: "+960", name: "Maldives" },
  { iso: "MW", dialCode: "+265", name: "Malawi" },
  { iso: "MX", dialCode: "+52", name: "Mexico" },
  { iso: "MY", dialCode: "+60", name: "Malaysia" },
  { iso: "MZ", dialCode: "+258", name: "Mozambique" },
  { iso: "NA", dialCode: "+264", name: "Namibia" },
  { iso: "NE", dialCode: "+227", name: "Niger" },
  { iso: "NG", dialCode: "+234", name: "Nigeria" },
  { iso: "NI", dialCode: "+505", name: "Nicaragua" },
  { iso: "NL", dialCode: "+31", name: "Netherlands" },
  { iso: "NO", dialCode: "+47", name: "Norway" },
  { iso: "NP", dialCode: "+977", name: "Nepal" },
  { iso: "NR", dialCode: "+674", name: "Nauru" },
  { iso: "NZ", dialCode: "+64", name: "New Zealand" },
  { iso: "OM", dialCode: "+968", name: "Oman" },
  { iso: "PA", dialCode: "+507", name: "Panama" },
  { iso: "PE", dialCode: "+51", name: "Peru" },
  { iso: "PG", dialCode: "+675", name: "Papua New Guinea" },
  { iso: "PH", dialCode: "+63", name: "Philippines" },
  { iso: "PK", dialCode: "+92", name: "Pakistan" },
  { iso: "PL", dialCode: "+48", name: "Poland" },
  { iso: "PT", dialCode: "+351", name: "Portugal" },
  { iso: "PW", dialCode: "+680", name: "Palau" },
  { iso: "PY", dialCode: "+595", name: "Paraguay" },
  { iso: "QA", dialCode: "+974", name: "Qatar" },
  { iso: "RO", dialCode: "+40", name: "Romania" },
  { iso: "RS", dialCode: "+381", name: "Serbia" },
  { iso: "RU", dialCode: "+7", name: "Russia" },
  { iso: "RW", dialCode: "+250", name: "Rwanda" },
  { iso: "SA", dialCode: "+966", name: "Saudi Arabia" },
  { iso: "SB", dialCode: "+677", name: "Solomon Islands" },
  { iso: "SC", dialCode: "+248", name: "Seychelles" },
  { iso: "SD", dialCode: "+249", name: "Sudan" },
  { iso: "SE", dialCode: "+46", name: "Sweden" },
  { iso: "SG", dialCode: "+65", name: "Singapore" },
  { iso: "SI", dialCode: "+386", name: "Slovenia" },
  { iso: "SK", dialCode: "+421", name: "Slovakia" },
  { iso: "SL", dialCode: "+232", name: "Sierra Leone" },
  { iso: "SM", dialCode: "+378", name: "San Marino" },
  { iso: "SN", dialCode: "+221", name: "Senegal" },
  { iso: "SO", dialCode: "+252", name: "Somalia" },
  { iso: "SR", dialCode: "+597", name: "Suriname" },
  { iso: "SS", dialCode: "+211", name: "South Sudan" },
  { iso: "ST", dialCode: "+239", name: "São Tomé and Príncipe" },
  { iso: "SV", dialCode: "+503", name: "El Salvador" },
  { iso: "SY", dialCode: "+963", name: "Syria" },
  { iso: "SZ", dialCode: "+268", name: "Eswatini" },
  { iso: "TD", dialCode: "+235", name: "Chad" },
  { iso: "TG", dialCode: "+228", name: "Togo" },
  { iso: "TH", dialCode: "+66", name: "Thailand" },
  { iso: "TJ", dialCode: "+992", name: "Tajikistan" },
  { iso: "TL", dialCode: "+670", name: "Timor-Leste" },
  { iso: "TM", dialCode: "+993", name: "Turkmenistan" },
  { iso: "TN", dialCode: "+216", name: "Tunisia" },
  { iso: "TO", dialCode: "+676", name: "Tonga" },
  { iso: "TR", dialCode: "+90", name: "Turkey" },
  { iso: "TT", dialCode: "+1868", name: "Trinidad and Tobago" },
  { iso: "TV", dialCode: "+688", name: "Tuvalu" },
  { iso: "TZ", dialCode: "+255", name: "Tanzania" },
  { iso: "UA", dialCode: "+380", name: "Ukraine" },
  { iso: "UG", dialCode: "+256", name: "Uganda" },
  { iso: "US", dialCode: "+1", name: "United States" },
  { iso: "UY", dialCode: "+598", name: "Uruguay" },
  { iso: "UZ", dialCode: "+998", name: "Uzbekistan" },
  { iso: "VC", dialCode: "+1784", name: "Saint Vincent and the Grenadines" },
  { iso: "VE", dialCode: "+58", name: "Venezuela" },
  { iso: "VN", dialCode: "+84", name: "Vietnam" },
  { iso: "VU", dialCode: "+678", name: "Vanuatu" },
  { iso: "WS", dialCode: "+685", name: "Samoa" },
  { iso: "YE", dialCode: "+967", name: "Yemen" },
  { iso: "ZA", dialCode: "+27", name: "South Africa" },
  { iso: "ZM", dialCode: "+260", name: "Zambia" },
  { iso: "ZW", dialCode: "+263", name: "Zimbabwe" },
];

/** Convert a 2-letter ISO code to a flag emoji (e.g. "CL" → "🇨🇱") */
export function isoToFlag(iso: string): string {
  return iso
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397))
    .join("");
}

/** Get dial code by ISO code (e.g. "CL" → "+56") */
export function getDialCodeByIso(iso: string): string {
  return PHONE_PREFIXES.find((p) => p.iso === iso)?.dialCode ?? "";
}

/**
 * Split a stored phone string like "+56912345678" into its prefix and bare number.
 * Matches the longest prefix first to handle overlapping codes (e.g. "+1876" before "+1").
 */
export function splitPhoneNumber(fullPhone: string): {
  prefix: string;
  number: string;
} {
  if (!fullPhone.startsWith("+")) return { prefix: "", number: fullPhone };

  const sortedCodes = PHONE_PREFIXES.map((p) => p.dialCode).sort(
    (a, b) => b.length - a.length,
  );

  for (const code of sortedCodes) {
    if (fullPhone.startsWith(code)) {
      return { prefix: code, number: fullPhone.slice(code.length) };
    }
  }

  return { prefix: "", number: fullPhone };
}
