import Colors from "@/constants/Colors";
import { Droplets, Info, Leaf } from "lucide-react-native";
import React, { useEffect } from "react";
import { StyleSheet, Text, View } from "react-native";
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";
import Modal from "../shared/Modal/Modal";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface EnvironmentalImpactModalProps {
  isOpen?: boolean;
  onClose?: () => void;
  environmentalImpact: {
    totalCo2SavingsKG: number;
    totalWaterSavingsLT: number;
    materialBreakdown: Array<{
      materialType: string;
      percentage: number;
      weightKG: number;
      co2SavingsKG: number;
      waterSavingsLT: number;
    }>;
  };
  co2SavingsTitle?: string;
  waterSavingsTitle?: string;
  weightLabel?: string;
  co2SavingsLabel?: string;
  waterSavingsLabel?: string;
  materialBreakdownLabel?: string;
  co2EquivalenceLabel?: string;
  waterEquivalenceLabel?: string;
  infoText?: string;
  carDistanceLabel?: string;
  showerCountLabel?: string;
}

// ─── Helper ───────────────────────────────────────────────────────────────────

function formatNumber(num: number): string {
  return num.toLocaleString("es-CL", {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  });
}

// ─── Progress bar sub-component ───────────────────────────────────────────────

function ProgressBar({ percentage }: { percentage: number }) {
  const width = useSharedValue(0);

  useEffect(() => {
    width.value = withTiming(percentage, { duration: 600 });
  }, [percentage]);

  const barStyle = useAnimatedStyle(() => ({
    width: `${width.value}%`,
  }));

  return (
    <View style={styles.progressTrack}>
      <Animated.View style={[styles.progressFill, barStyle]} />
    </View>
  );
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function EnvironmentalImpactModal({
  isOpen,
  onClose,
  environmentalImpact,
  co2SavingsTitle = "CO₂ Savings",
  waterSavingsTitle = "Water Savings",
  weightLabel = "Weight",
  co2SavingsLabel = "CO₂ Saved",
  waterSavingsLabel = "Water Saved",
  materialBreakdownLabel = "Material Breakdown",
  co2EquivalenceLabel = "Equivalent to",
  waterEquivalenceLabel = "Equivalent to",
  infoText = "These values are estimates based on the savings generated by reusing products instead of manufacturing new ones.",
  carDistanceLabel = " by car",
  showerCountLabel = " showers",
}: EnvironmentalImpactModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Detailed Environmental Impact" size="md">
      <View style={styles.content}>

        {/* ── Summary cards ─────────────────────────────────────────── */}
        <View style={styles.summaryRow}>
          {/* CO₂ card */}
          <View style={[styles.summaryCard, styles.co2Card]}>
            <View style={styles.summaryHeader}>
              <Leaf size={18} color={Colors.success} strokeWidth={2} />
              <Text style={styles.summaryTitle}>{co2SavingsTitle}</Text>
            </View>
            <Text style={[styles.summaryValue, { color: Colors.success }]}>
              {formatNumber(environmentalImpact.totalCo2SavingsKG)} kg
            </Text>
            <Text style={styles.summaryEquivalence}>
              {co2EquivalenceLabel}{" "}
              {formatNumber(environmentalImpact.totalCo2SavingsKG * 4.5)} km
              {carDistanceLabel}
            </Text>
          </View>

          {/* Water card */}
          <View style={[styles.summaryCard, styles.waterCard]}>
            <View style={styles.summaryHeader}>
              <Droplets size={18} color={Colors.info} strokeWidth={2} />
              <Text style={styles.summaryTitle}>{waterSavingsTitle}</Text>
            </View>
            <Text style={[styles.summaryValue, { color: Colors.info }]}>
              {formatNumber(environmentalImpact.totalWaterSavingsLT)} L
            </Text>
            <Text style={styles.summaryEquivalence}>
              {waterEquivalenceLabel}{" "}
              {formatNumber(environmentalImpact.totalWaterSavingsLT / 8)}
              {showerCountLabel}
            </Text>
          </View>
        </View>

        {/* ── Material breakdown ────────────────────────────────────── */}
        {environmentalImpact.materialBreakdown.length > 0 && (
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <Info size={18} color={Colors.foreground} strokeWidth={2} />
              <Text style={styles.sectionTitle}>{materialBreakdownLabel}</Text>
            </View>

            <View style={styles.materialList}>
              {environmentalImpact.materialBreakdown.map((material, index) => (
                <View key={index} style={styles.materialCard}>
                  {/* Name + percentage */}
                  <View style={styles.materialHeader}>
                    <Text style={styles.materialName}>{material.materialType}</Text>
                    <Text style={styles.materialPercentage}>
                      {material.percentage.toFixed(1)}%
                    </Text>
                  </View>

                  {/* 3-col stats */}
                  <View style={styles.statsRow}>
                    <View style={styles.statItem}>
                      <Text style={styles.statLabel}>{weightLabel}</Text>
                      <Text style={styles.statValue}>
                        {formatNumber(material.weightKG)} kg
                      </Text>
                    </View>
                    <View style={styles.statItem}>
                      <Text style={styles.statLabel}>{co2SavingsLabel}</Text>
                      <Text style={[styles.statValue, { color: Colors.success }]}>
                        {formatNumber(material.co2SavingsKG)} kg
                      </Text>
                    </View>
                    <View style={styles.statItem}>
                      <Text style={styles.statLabel}>{waterSavingsLabel}</Text>
                      <Text style={[styles.statValue, { color: Colors.info }]}>
                        {formatNumber(material.waterSavingsLT)} L
                      </Text>
                    </View>
                  </View>

                  {/* Progress bar */}
                  <ProgressBar percentage={material.percentage} />
                </View>
              ))}
            </View>
          </View>
        )}

        {/* ── Info footer ───────────────────────────────────────────── */}
        <View style={styles.infoFooter}>
          <Info size={14} color={Colors.primary} strokeWidth={2} style={styles.infoIcon} />
          <Text style={styles.infoText}>{infoText}</Text>
        </View>

      </View>
    </Modal>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  content: {
    gap: 20,
  },
  // Summary
  summaryRow: {
    flexDirection: "row",
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    borderRadius: 10,
    padding: 14,
    gap: 4,
  },
  co2Card: {
    backgroundColor: `${Colors.success}1A`,
  },
  waterCard: {
    backgroundColor: `${Colors.info}1A`,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  summaryTitle: {
    fontSize: 13,
    fontFamily: "Cabin_500Medium",
    color: Colors.foregroundSecondary,
    flexShrink: 1,
  },
  summaryValue: {
    fontSize: 22,
    fontFamily: "Cabin_700Bold",
    letterSpacing: -0.5,
  },
  summaryEquivalence: {
    fontSize: 11,
    fontFamily: "Cabin_400Regular",
    color: Colors.foregroundSecondary,
    lineHeight: 15,
  },
  // Section
  section: {
    gap: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Cabin_700Bold",
    color: Colors.foreground,
  },
  // Material cards
  materialList: {
    gap: 10,
  },
  materialCard: {
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: 10,
    padding: 14,
    gap: 10,
  },
  materialHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  materialName: {
    fontSize: 14,
    fontFamily: "Cabin_600SemiBold",
    color: Colors.foreground,
    flex: 1,
  },
  materialPercentage: {
    fontSize: 16,
    fontFamily: "Cabin_700Bold",
    color: Colors.primary,
  },
  // Stat columns
  statsRow: {
    flexDirection: "row",
    gap: 8,
  },
  statItem: {
    flex: 1,
    gap: 2,
  },
  statLabel: {
    fontSize: 11,
    fontFamily: "Cabin_400Regular",
    color: Colors.foregroundSecondary,
  },
  statValue: {
    fontSize: 13,
    fontFamily: "Cabin_600SemiBold",
    color: Colors.foreground,
  },
  // Progress bar
  progressTrack: {
    height: 6,
    backgroundColor: `${Colors.primary}1A`,
    borderRadius: 99,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: Colors.primary,
    borderRadius: 99,
  },
  // Info footer
  infoFooter: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: `${Colors.primary}0D`,
    borderRadius: 10,
    padding: 14,
  },
  infoIcon: {
    marginTop: 1,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Cabin_400Regular",
    color: Colors.foregroundSecondary,
    lineHeight: 18,
  },
});
